version: "3.9"

services:
  postgres_test:
    image: postgres:16.2-bookworm
    restart: always
    env_file:
      - .secrets
    environment:
      POSTGRES_DB: foodgood
    ports:
      - "5433:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      interval: 1s
volumes:
  postgresql:
